apiVersion: codius.org/v1
kind: Podius
metadata:
  name: example-podius
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    env:
    - name: CODIUS_PUBLIC_URI
      value: https://c8s.example.com
    - name: CODIUS_SECRET
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
  port: 80
